export const stacklevel = [
    {link: "/assets/html5-original-wordmark.svg", name: "HTML", level: 4, color: "#FC6D26"},
    {link: "/assets/javascript-original.svg", name: "JavaScript", level: 4, color: "#FFCF46"},
    {link: "/assets/mysql-original-wordmark.svg", name: "MySQL", level: 2, color: "#FCA326"},
    {link: "/assets/css3-original-wordmark.svg", name: "CSS", level: 4, color: "#1572B6"},
    {link: "/assets/typescript-original.svg", name: "TypeScript", level: 3, color: "#007ACC"},
    {link: "/assets/git-original-wordmark.svg", name: "GIT", level: 4, color: "#E24329"},
    {link: "/assets/figma-original.svg", name: "Figma", level: 4, color: "#A600E0"},
    {link: "/assets/nodejs-original-wordmark.svg", name: "Node.js", level: 2, color: "#83CD29"},
    {link: "/assets/jamstack-original-wordmark.svg", name: "JAMstack", level: 4, color: "#F0047F"},
    {link: "/assets/photoshop-plain.svg", name: "Photoshop", level: 4, color: "#386F9F"},
    {link: "/assets//python-original-wordmark.svg", name: "Python", level: 2, color: "#FFCF46"},
    {link: "/assets/gitlab-original-wordmark.svg", name: "Gitlab", level: 3, color: "#F24E1E"},
    {link: "/assets/sass-original.svg", name: "SASS", level: 4, color: "#CB6699"},
    {link: "public/assets/react-original-wordmark.svg", name: "ReactJS", level: 3, color: "#61DAFB"},
    {link: "public/assets/github-original-wordmark.svg", name: "GitHub", level: 3, color: "#0ACF83"},
];