# Simple workflow for deploying content to Netlify
name: Build and Deploy to Netlify

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  # Build frontend app
  build-frontend-app:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Last Branch Commit
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
      - uses: actions/setup-node@v3.5.1
        
      - name: Cache
      - uses: actions/cache@v3.0.11
        
      - name: Install Dependencies
        run: yarn

      - name: Run Build 
        run: yarn build
