name: Build and Deploy to Netlify
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install yarn
        run: npm install yarn -g
      - name: Install project dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Check
        run: ls
  
